RETRO68 ?= $(HOME)/downloads/Retro68-build/toolchain
PREFIX=$(RETRO68)/m68k-apple-macos
CC=$(RETRO68)/bin/m68k-apple-macos-gcc
CXX=$(RETRO68)/bin/m68k-apple-macos-g++
REZ=$(RETRO68)/bin/Rez

BUILD_DIR ?= build/m68k

CFLAGS = -D__MACOS__ -DFORCE2X -Os -fdata-sections -ffunction-sections
CXXFLAGS = $(CFLAGS)

LDFLAGS=-lRetroConsole -lSDL -Wl,--as-needed -Wl,--gc-sections
RINCLUDES=$(PREFIX)/RIncludes
REZFLAGS=-I$(RINCLUDES)

CFLAGS += $(DEFS)

all: $(BUILD_DIR)/MemebooruM68K.bin $(BUILD_DIR)/MemebooruM68K.APPL $(BUILD_DIR)/MemebooruM68K.dsk

$(BUILD_DIR)/MemebooruM68K.bin $(BUILD_DIR)/MemebooruM68K.APPL $(BUILD_DIR)/MemebooruM68K.dsk: $(BUILD_DIR)/MemebooruM68K.code.bin
	$(REZ) $(REZFLAGS) \
		--copy "$(BUILD_DIR)/MemebooruM68K.code.bin" \
		"./Retro68APPL.r" \
		-t "APPL" -c "????" \
		-o "$(BUILD_DIR)/MemebooruM68K.bin" --cc "$(BUILD_DIR)/MemebooruM68K.APPL" --cc "$(BUILD_DIR)/MemebooruM68K.dsk"

$(BUILD_DIR)/MemebooruM68K.code.bin: $(BUILD_DIR)/main.o
	$(CXX) $(CXXFLAGS) $(BUILD_DIR)/main.o -o $@ $(LDFLAGS)	# C++ used for linking because RetroConsole needs it

$(BUILD_DIR)/main.o: main.c stb_image.h stb_easy_font.h mac_file_dialog.h
	@mkdir -p "$(BUILD_DIR)"
	$(CC) $(CFLAGS) -c -o $@ main.c

.PHONY: clean all
clean:
	rm -rf "$(BUILD_DIR)"
