RETRO68 ?= $(HOME)/Downloads/Retro68-build/toolchain
PREFIX=$(RETRO68)/powerpc-apple-macos
CC=$(RETRO68)/bin/powerpc-apple-macos-gcc
CXX=$(RETRO68)/bin/powerpc-apple-macos-g++
REZ=$(RETRO68)/bin/Rez
MAKEPEF = $(RETRO68)/bin/MakePEF

BUILD_DIR ?= build/ppc
OBJS = $(BUILD_DIR)/main.o $(BUILD_DIR)/store.o $(BUILD_DIR)/views.o $(BUILD_DIR)/textedit.o

CFLAGS = -D__MACOS__ -DSDLMIX_SOUND -DSCALING -Ofast -fdata-sections -ffunction-sections
CXXFLAGS = $(CFLAGS)

LDFLAGS=-L$(PREFIX)/lib -lRetroConsole -lm -lSDL -lDialogsLib -lQuickTimeLib -Wl,--as-needed -Wl,--gc-sections
RINCLUDES=$(PREFIX)/RIncludes
REZFLAGS=-I$(RINCLUDES)

CFLAGS += $(DEFS)

all: $(BUILD_DIR)/MemebooruPPC.bin $(BUILD_DIR)/MemebooruPPC.APPL $(BUILD_DIR)/MemebooruPPC.dsk

$(BUILD_DIR)/MemebooruPPC.bin $(BUILD_DIR)/MemebooruPPC.APPL $(BUILD_DIR)/MemebooruPPC.dsk: $(BUILD_DIR)/MemebooruPPC.xcoff
	$(MAKEPEF) "$(BUILD_DIR)/MemebooruPPC.xcoff" -o "$(BUILD_DIR)/MemebooruPPC.pef"
	$(REZ) $(REZFLAGS) ./SDL.r -I$(RINCLUDES) -DCFRAG_NAME="\"MemebooruPPC\"" \
		-o "$(BUILD_DIR)/MemebooruPPC.bin" \
		--cc "$(BUILD_DIR)/MemebooruPPC.dsk" \
		--cc "$(BUILD_DIR)/MemebooruPPC.APPL" \
		--cc "$(BUILD_DIR)/%MemebooruPPC.ad" \
		-t APPL -c ???? \
		--data "$(BUILD_DIR)/MemebooruPPC.pef"

$(BUILD_DIR)/MemebooruPPC.xcoff: $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $@ $(LDFLAGS)	# C++ used for linking because RetroConsole needs it

$(BUILD_DIR)/main.o: main.c app.h store.h views.h textedit.h stb_image.h stb_easy_font.h mac_file_dialog.h
	@mkdir -p "$(BUILD_DIR)"
	$(CC) $(CFLAGS) -c -o $@ main.c

$(BUILD_DIR)/store.o: store.c app.h store.h
	@mkdir -p "$(BUILD_DIR)"
	$(CC) $(CFLAGS) -c -o $@ store.c

$(BUILD_DIR)/views.o: views.c app.h views.h store.h textedit.h
	@mkdir -p "$(BUILD_DIR)"
	$(CC) $(CFLAGS) -c -o $@ views.c

$(BUILD_DIR)/textedit.o: textedit.c app.h textedit.h
	@mkdir -p "$(BUILD_DIR)"
	$(CC) $(CFLAGS) -c -o $@ textedit.c

.PHONY: clean all
clean:
	rm -rf "$(BUILD_DIR)"
